feat: add graceful component resolver

diff --git a/bin/get_bashed_component b/bin/get_bashed_component
--- a/bin/get_bashed_component
+++ b/bin/get_bashed_component
@@ -33,13 +33,13 @@ if [[ $# -eq 0 ]]; then
 fi
 
 GET_BASHED_HOME="${GET_BASHED_HOME:-$HOME/.get-bashed}"
-BASH_IT="$GET_BASHED_HOME/vendor/bash-it"
-if [[ -r "$BASH_IT/bash_it.sh" ]]; then
+HELPERS="$GET_BASHED_HOME/installers/_helpers.sh"
+if [[ -r "$HELPERS" ]]; then
   # shellcheck disable=SC1090
-  source "$BASH_IT/bash_it.sh"
+  source "$HELPERS"
 else
-  echo "bash-it not found at $BASH_IT. Install with: ./install.sh --install bash_it" >&2
+  echo "helpers not found at $HELPERS" >&2
   exit 1
 fi
 
-NO_COLOR=1 bash-it search "$@" "--${action}"
+component_install "$action" "$@"
